swagger: '2.0'
info:
  title: groq
  description: ''
  version: '1.0'
host: api.groq.com
basePath: /openai/v1
schemes:
  - https
consumes: []
produces: []
paths:
  /chat/completions:
    post:
      responses:
        default:
          description: default
          schema:
            type: object
            properties:
              id:
                type: string
                description: id
              object:
                type: string
                description: object
              created:
                type: integer
                format: int32
                description: created
              model:
                type: string
                description: model
              choices:
                type: array
                items:
                  type: object
                  properties:
                    index:
                      type: integer
                      format: int32
                      description: index
                    message:
                      type: object
                      properties:
                        role:
                          type: string
                          description: role
                        content:
                          type: string
                          description: content
                      description: message
                    logprobs:
                      type: string
                      description: logprobs
                    finish_reason:
                      type: string
                      description: finish_reason
                description: choices
              usage:
                type: object
                properties:
                  prompt_tokens:
                    type: integer
                    format: int32
                    description: prompt_tokens
                  prompt_time:
                    type: number
                    format: float
                    description: prompt_time
                  completion_tokens:
                    type: integer
                    format: int32
                    description: completion_tokens
                  completion_time:
                    type: number
                    format: float
                    description: completion_time
                  total_tokens:
                    type: integer
                    format: int32
                    description: total_tokens
                  total_time:
                    type: number
                    format: float
                    description: total_time
                description: usage
              system_fingerprint:
                type: string
                description: system_fingerprint
              x_groq:
                type: object
                properties:
                  id:
                    type: string
                    description: id
                description: x_groq
      summary: chat
      description: chat
      operationId: Chat
      x-ms-visibility: important
      parameters:
        - name: Content-Type
          in: header
          required: true
          type: string
          default: application/json
          x-ms-visibility: internal
        - name: body
          in: body
          required: true
          schema:
            type: object
            properties: {}
            x-ms-visibility: important
          x-ms-visibility: important
  /models:
    get:
      responses:
        default:
          description: default
          schema: {}
      summary: List models
      description: List models
      operationId: List_models
      parameters: []
definitions: {}
parameters: {}
responses: {}
securityDefinitions: {}
security: []
tags: []
