swagger: '2.0'
info:
  title: OpenAI-Global
  description: >-
    This is a GLOBAL Connector meaning you embed the API Key into each of the
    definitions as a hidden attribute with a default value. To connect to the
    OpenAI API and use the Power of GPT3, API key must be entered as "Bearer
    YOUR_API_KEY"
  version: '2.1'
  contact:
    name: David Soden & Robin Rosengrün
    url: https://DavidSoden.com
host: api.openai.com
basePath: /
schemes:
  - https
consumes: []
produces: []
paths:
  /v1/engines/{engine}/completions:
    post:
      responses:
        default:
          description: default
          schema:
            type: object
            properties:
              id:
                type: string
                description: id
              object:
                type: string
                description: object
              created:
                type: integer
                format: int32
                description: created
              model:
                type: string
                description: model
              choices:
                type: array
                items:
                  type: object
                  properties:
                    text:
                      type: string
                      description: text
                    index:
                      type: integer
                      format: int32
                      description: index
                    logprobs:
                      type: string
                      description: logprobs
                    finish_reason:
                      type: string
                      description: finish_reason
                description: choices
              usage:
                type: object
                properties:
                  prompt_tokens:
                    type: integer
                    format: int32
                    description: prompt_tokens
                  completion_tokens:
                    type: integer
                    format: int32
                    description: completion_tokens
                  total_tokens:
                    type: integer
                    format: int32
                    description: total_tokens
                description: usage
          headers:
            '{':
              description: '{'
              type: string
            '"cache-control"':
              description: '"cache-control"'
              type: string
            '"content-length"':
              description: '"content-length"'
              type: string
            '"content-type"':
              description: '"content-type"'
              type: string
            '"date"':
              description: '"date"'
              type: string
            '"openai-model"':
              description: '"openai-model"'
              type: string
            '"openai-organization"':
              description: '"openai-organization"'
              type: string
            '"openai-processing-ms"':
              description: '"openai-processing-ms"'
              type: string
            '"openai-version"':
              description: '"openai-version"'
              type: string
            '"strict-transport-security"':
              description: '"strict-transport-security"'
              type: string
            '"vary"':
              description: '"vary"'
              type: string
            '"x-ms-apihub-cached-response"':
              description: '"x-ms-apihub-cached-response"'
              type: string
            '"x-ms-apihub-obo"':
              description: '"x-ms-apihub-obo"'
              type: string
            '"x-request-id"':
              description: '"x-request-id"'
              type: string
            '}':
              description: '}'
              type: string
      summary: GPT3 Completes your prompt
      description: GPT3 Completes your prompt
      operationId: Completion
      x-ms-visibility: important
      parameters:
        - name: engine
          in: path
          required: true
          type: string
          default: text-davinci-003
          description: >-
            The used engine, choose between text-davinci-002/003,
            text-curie-001, text-babbage-001, text-ada-001
          x-ms-summary: Engine
          x-ms-visibility: important
          enum:
            - text-davinci-003
            - text-davinci-002
            - text-curie-001
            - text-babbage-001
            - text-ada-001
        - name: body
          in: body
          required: false
          schema:
            type: object
            properties:
              prompt:
                type: string
                description: Text that will be completed by GPT3
                title: prompt
                default: >-
                  What is your favorite animal and why? Tell me also about the
                  size and weight of this animal.
              'n':
                type: integer
                format: int32
                description: How many completions to generate for each prompt
                title: ''
                default: 1
              best_of:
                type: integer
                format: int32
                description: >-
                  If set to more than 1, generates multiple completions
                  server-side and returns the "best". Must be greater than "n".
                  Use with caution, can consume a lot of tokens.
                title: ''
                default: 1
              temperature:
                type: integer
                format: int32
                description: >-
                  Higher values means the model will take more risks. Try 0.9
                  for more creative applications, and 0 (argmax sampling) for
                  ones with a well-defined answer. Use this OR top p
                title: temperature
                default: 1
              max_tokens:
                type: integer
                format: int32
                description: >-
                  One token equals roughly 4 characters of text (up to 4000
                  tokens between prompt and completion)
                title: max tokens
                default: 100
              top_p:
                type: integer
                format: int32
                description: >-
                  An alternative to sampling with temperature, called nucleus
                  sampling, where the model considers the results of the tokens
                  with top_p probability mass. So 0.1 means only the tokens
                  comprising the top 10% probability mass are considered.
                title: top_p
              frequency_penalty:
                type: integer
                format: int32
                description: >-
                  Number between -2.0 and 2.0. Positive values penalize new
                  tokens based on their existing frequency in the text so far,
                  decreasing the models likelihood to repeat the same line
                  verbatim.
                title: frequency penalty
                default: 0
              presence_penalty:
                type: integer
                format: int32
                description: >-
                  Number between -2.0 and 2.0. Positive values penalize new
                  tokens based on whether they appear in the text so far,
                  increasing the models likelihood to talk about new topics.
                title: presence_penalty
                default: 0
              user:
                type: string
                description: >-
                  A unique identifier representing your end-user, which will
                  help OpenAI to monitor and detect abuse
                title: user
              stop:
                type: array
                items:
                  type: string
                description: stop
            required:
              - prompt
  /v1/moderations:
    post:
      responses:
        default:
          description: default
          schema:
            type: object
            properties:
              id:
                type: string
                description: id
              model:
                type: string
                description: model
              results:
                type: array
                items:
                  type: object
                  properties:
                    flagged:
                      type: boolean
                      description: flagged
                    categories:
                      type: object
                      properties:
                        sexual:
                          type: boolean
                          description: sexual
                        hate:
                          type: boolean
                          description: hate
                        violence:
                          type: boolean
                          description: violence
                        self-harm:
                          type: boolean
                          description: self-harm
                        sexual/minors:
                          type: boolean
                          description: sexual/minors
                        hate/threatening:
                          type: boolean
                          description: hate/threatening
                        violence/graphic:
                          type: boolean
                          description: violence/graphic
                      description: categories
                    category_scores:
                      type: object
                      properties:
                        sexual:
                          type: number
                          format: float
                          description: sexual
                        hate:
                          type: number
                          format: float
                          description: hate
                        violence:
                          type: number
                          format: float
                          description: violence
                        self-harm:
                          type: number
                          format: float
                          description: self-harm
                        sexual/minors:
                          type: number
                          format: float
                          description: sexual/minors
                        hate/threatening:
                          type: number
                          format: float
                          description: hate/threatening
                        violence/graphic:
                          type: number
                          format: float
                          description: violence/graphic
                      description: category_scores
                description: results
      summary: Moderation
      description: >-
        Given a input text, outputs if the model classifies it as violating
        OpenAI's content policy.
      operationId: Moderation
      parameters:
        - name: Content-Type
          in: header
          required: true
          type: string
          default: application/json
          x-ms-visibility: internal
        - name: body
          in: body
          required: true
          schema:
            type: object
            properties:
              input:
                type: string
                description: input
                title: ''
                x-ms-visibility: important
                default: I will kill them
            required:
              - input
            x-ms-visibility: important
          x-ms-visibility: important
definitions: {}
parameters: {}
responses: {}
securityDefinitions: {}
security: []
tags: []
